### PR TITLE
Add automation for US01

### PR DESCRIPTION
**Pull request by kpollina**

### CODE REVIEW

**Review by UlianaCh — COMMENTED** [review]
just a feedback: in your feature scenario you don't have to add examples of username and password, just userType is sufficient if you want too edit first step wher it said Given - it can just say Given user logged in as "<userType>" , and then there is already ready method for in in our common login page so it will pull the username and password from configuration file and read it, (unless you wanted to test with different passwords and username of course), also curious why did you have to modify BasePage? I think you are supposed to create another page for your US01 where you can put your locators in (maybe someone else can clarify?

**Review by seymasonmez — COMMENTED** [review]
Polina, can you please fix the BasePage class? Since it is a common page we shouldn't touch it while we are working on our local branch.For this, it may be a good idea to create your own page class to store your web elements.Thank you!

**Comment by kpollina** [comment]
> Polina, can you please fix the BasePage class? Since it is a common page we shouldn't touch it while we are working on our local branch.For this, it may be a good idea to create your own page class to store your web elements.Thank you!

>Updated.

**Comment by kpollina** [comment]
> just a feedback: in your feature scenario you don't have to add examples of username and password, just userType is sufficient if you want too edit first step wher it said Given - it can just say Given user logged in as "" , and then there is already ready method for in in our common login page so it will pull the username and password from configuration file and read it, (unless you wanted to test with different passwords and username of course), also curious why did you have to modify BasePage? I think you are supposed to create another page for your US01 where you can put your locators in (maybe someone else can clarify?

>"In cucumber, Data-Driven Testing (DDT) can be achieved through various methods, and one common approach is to use Scenario Outline and Examples tables in feature files. This allows you to parameterize your scenarios and run them with different sets of test data" - following this path

**Pull request closed without merging**
